/**
 * Resolves a lucide icon's kebab-case name into a Vue component.
 *
 * MenuItem.icon arrives from the backend as a string — 'file-text', 'users'.
 * So as not to drag the whole of lucide-vue-next into the bundle, we keep a
 * whitelist of the popular names, and a host extends it through
 * registerIcon(name, comp).
 *
 * A name that is not found falls back to Box, so a sidebar item is never
 * rendered without an icon.
 */
import type { Component } from 'vue'
import {
  Activity,
  AlertCircle,
  Archive,
  Award,
  BarChart3,
  Bell,
  Blocks,
  Book,
  Bookmark,
  BookOpen,
  Bot,
  Box,
  Boxes,
  Briefcase,
  Bug,
  Building,
  Building2,
  Calendar,
  CalendarDays,
  ChartBar,
  ChartLine,
  ChartPie,
  Check,
  CheckCircle,
  ClipboardList,
  Clock,
  Code,
  Cog,
  Coins,
  Columns3,
  Command,
  Copy,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Download,
  Euro,
  Eye,
  FileClock,
  FileCode,
  Files,
  FileText,
  Filter,
  Flag,
  Folder,
  FolderOpen,
  FolderTree,
  Gauge,
  Gift,
  Globe,
  Grid,
  HardDrive,
  Hash,
  Heart,
  HelpCircle,
  History,
  Home,
  Image,
  Images,
  Inbox,
  Info,
  Key,
  Languages,
  Layers,
  Layout,
  LayoutDashboard,
  LayoutGrid,
  LifeBuoy,
  LineChart,
  Link,
  List,
  ListChecks,
  ListTree,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Monitor,
  Moon,
  Newspaper,
  Package,
  Palette,
  Paperclip,
  Pencil,
  Percent,
  Phone,
  PieChart,
  Play,
  Plug,
  Plus,
  Puzzle,
  Receipt,
  RefreshCw,
  Rocket,
  RotateCcw,
  Search,
  Send,
  Server,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sliders,
  Sparkles,
  Star,
  Store,
  Sun,
  Table,
  Tag,
  Tags,
  Target,
  Terminal,
  Trash2,
  TrendingUp,
  Truck,
  Upload,
  User,
  UserCircle,
  UserCog,
  UserPlus,
  Users,
  Wallet,
  Webhook,
  Workflow,
  Wrench,
  XCircle,
  Zap,
} from 'lucide-vue-next'

const REGISTRY: Record<string, Component> = {
  'activity': Activity,
  'alert-circle': AlertCircle,
  'archive': Archive,
  'award': Award,
  'bar-chart': BarChart3,
  'bar-chart-3': BarChart3,
  'bell': Bell,
  'blocks': Blocks,
  'book': Book,
  'book-open': BookOpen,
  'bookmark': Bookmark,
  'bot': Bot,
  'box': Box,
  'boxes': Boxes,
  'briefcase': Briefcase,
  'bug': Bug,
  'building': Building,
  'building-2': Building2,
  'calendar': Calendar,
  'calendar-days': CalendarDays,
  'chart-bar': ChartBar,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  'check': Check,
  'check-circle': CheckCircle,
  'clipboard-list': ClipboardList,
  'clock': Clock,
  'code': Code,
  'cog': Cog,
  'coins': Coins,
  'columns': Columns3,
  'command': Command,
  'copy': Copy,
  'cpu': Cpu,
  'credit-card': CreditCard,
  'cube': Box,
  'database': Database,
  'dollar-sign': DollarSign,
  'download': Download,
  'euro': Euro,
  'eye': Eye,
  'file': FileText,
  'file-clock': FileClock,
  'file-code': FileCode,
  'file-text': FileText,
  'files': Files,
  'filter': Filter,
  'flag': Flag,
  'folder': Folder,
  'folder-open': FolderOpen,
  'folder-tree': FolderTree,
  'gauge': Gauge,
  'gift': Gift,
  'globe': Globe,
  'grid': Grid,
  'hard-drive': HardDrive,
  'hash': Hash,
  'health-check': CheckCircle,
  'heart': Heart,
  'help-circle': HelpCircle,
  'history': History,
  'home': Home,
  'image': Image,
  'images': Images,
  'inbox': Inbox,
  'info': Info,
  'key': Key,
  'languages': Languages,
  'layers': Layers,
  'layout': Layout,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  'life-buoy': LifeBuoy,
  'line-chart': LineChart,
  'link': Link,
  'list': List,
  'list-checks': ListChecks,
  'list-tree': ListTree,
  'lock': Lock,
  'log-out': LogOut,
  'mail': Mail,
  'map': Map,
  'map-pin': MapPin,
  'media': Image,
  'megaphone': Megaphone,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'monitor': Monitor,
  'moon': Moon,
  'newspaper': Newspaper,
  'notifications': Bell,
  'package': Package,
  'palette': Palette,
  'paperclip': Paperclip,
  'pencil': Pencil,
  'percent': Percent,
  'phone': Phone,
  'pie-chart': PieChart,
  'play': Play,
  'plug': Plug,
  'plus': Plus,
  'puzzle': Puzzle,
  'receipt': Receipt,
  'refresh-cw': RefreshCw,
  'reports': BarChart3,
  'rocket': Rocket,
  'roles': Shield,
  'rotate-ccw': RotateCcw,
  'search': Search,
  'send': Send,
  'server': Server,
  'settings': Settings,
  'settings-2': Settings2,
  'shield': Shield,
  'shield-check': ShieldCheck,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  'sliders': Sliders,
  'sparkles': Sparkles,
  'star': Star,
  'store': Store,
  'sun': Sun,
  'table': Table,
  'tag': Tag,
  'tags': Tags,
  'target': Target,
  'terminal': Terminal,
  'trash-2': Trash2,
  'trending-up': TrendingUp,
  'truck': Truck,
  'upload': Upload,
  'user': User,
  'user-circle': UserCircle,
  'user-cog': UserCog,
  'user-plus': UserPlus,
  'users': Users,
  'wallet': Wallet,
  'webhook': Webhook,
  'workflow': Workflow,
  'wrench': Wrench,
  'x-circle': XCircle,
  'zap': Zap,
}

/**
 * Finds an icon by name, returning null when there is none — the caller
 * decides between the fallback and nothing at all.
 */
export function resolveIcon(name: string | null | undefined): Component | null {
  if (!name) return null
  return REGISTRY[name] ?? null
}

/** Registers an extra icon, from a host project. */
export function registerIcon(name: string, component: Component): void {
  REGISTRY[name] = component
}
