/**
 * Резолвер kebab-имени lucide-иконки → Vue-компонент.
 *
 * MenuItem.icon приходит из backend'а строкой (например 'file-text', 'users').
 * Чтобы не тащить весь lucide-vue-next в bundle — держим whitelist
 * популярных имён. Host может расширить через registerIcon(name, comp).
 *
 * Не найденное имя возвращает fallback (Box) — sidebar item никогда не
 * рендерится без иконки.
 */
import type { Component } from 'vue'
import {
  Activity,
  AlertCircle,
  Archive,
  BarChart3,
  Bell,
  Bookmark,
  Box,
  Briefcase,
  Calendar,
  CheckCircle,
  Clock,
  Code,
  Cog,
  Command,
  Database,
  Download,
  FileText,
  FileClock,
  Files,
  Flag,
  FolderOpen,
  Folder,
  Gauge,
  Globe,
  Grid,
  HardDrive,
  Hash,
  Heart,
  HelpCircle,
  History,
  Home,
  Image,
  Images,
  Inbox,
  Info,
  Key,
  Layers,
  LayoutDashboard,
  Layout,
  LifeBuoy,
  LineChart,
  Link,
  List,
  ListChecks,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Map,
  MessageSquare,
  Monitor,
  Package,
  Paperclip,
  PieChart,
  RefreshCw,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Sliders,
  Star,
  Store,
  Tag,
  Tags,
  Terminal,
  TrendingUp,
  Upload,
  User,
  UserCircle,
  Users,
  XCircle,
  Zap,
} from 'lucide-vue-next'

const REGISTRY: Record<string, Component> = {
  'activity': Activity,
  'alert-circle': AlertCircle,
  'archive': Archive,
  'bar-chart': BarChart3,
  'bar-chart-3': BarChart3,
  'bell': Bell,
  'bookmark': Bookmark,
  'box': Box,
  'briefcase': Briefcase,
  'calendar': Calendar,
  'check-circle': CheckCircle,
  'clock': Clock,
  'code': Code,
  'cog': Cog,
  'command': Command,
  'database': Database,
  'download': Download,
  'file': FileText,
  'file-text': FileText,
  'file-clock': FileClock,
  'files': Files,
  'flag': Flag,
  'folder': Folder,
  'folder-open': FolderOpen,
  'gauge': Gauge,
  'globe': Globe,
  'grid': Grid,
  'hard-drive': HardDrive,
  'hash': Hash,
  'health-check': CheckCircle,
  'heart': Heart,
  'help-circle': HelpCircle,
  'history': History,
  'home': Home,
  'image': Image,
  'images': Images,
  'inbox': Inbox,
  'info': Info,
  'key': Key,
  'layers': Layers,
  'layout': Layout,
  'layout-dashboard': LayoutDashboard,
  'life-buoy': LifeBuoy,
  'line-chart': LineChart,
  'link': Link,
  'list': List,
  'list-checks': ListChecks,
  'lock': Lock,
  'log-out': LogOut,
  'mail': Mail,
  'map': Map,
  'map-pin': MapPin,
  'media': Image,
  'message-square': MessageSquare,
  'monitor': Monitor,
  'notifications': Bell,
  'package': Package,
  'paperclip': Paperclip,
  'pie-chart': PieChart,
  'refresh-cw': RefreshCw,
  'reports': BarChart3,
  'roles': Shield,
  'search': Search,
  'send': Send,
  'server': Server,
  'settings': Settings,
  'shield': Shield,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  'sliders': Sliders,
  'star': Star,
  'store': Store,
  'tag': Tag,
  'tags': Tags,
  'terminal': Terminal,
  'trending-up': TrendingUp,
  'upload': Upload,
  'user': User,
  'user-circle': UserCircle,
  'users': Users,
  'x-circle': XCircle,
  'zap': Zap,
}

/**
 * Найти иконку по имени. Не найдена — null (вызывающий код решает рендерить
 * fallback или ничего).
 */
export function resolveIcon(name: string | null | undefined): Component | null {
  if (!name) return null
  return REGISTRY[name] ?? null
}

/** Зарегистрировать дополнительную иконку (host-проект). */
export function registerIcon(name: string, component: Component): void {
  REGISTRY[name] = component
}
